### PR TITLE
Fix index redirs

### LINKED ISSUE #657: redirect from /milestones/ to /milestones/latest/
I always end up in the wrong place typing in the url - /milestones/ seems like it should be the default location to me?

### PR DESCRIPTION
**Pull request by muffinresearch**
Fixes #657

### CODE REVIEW

File: pages/milestones/latest.js [hunk 1]
```diff
@@ -5,11 +5,22 @@ export default function Page() {
...
+  if (!props.query) {
+    props.query = {};
+  }
+
+  if (typeof props.query.dir === 'undefined') {
+    props.query.dir = 'asc';
+  }
+
+  if (typeof props.query.sort === 'undefined') {
+    props.query.sort = 'assignee';
```
Comment (eviljeff) [inline pages/milestones/latest.js:21]: `props.query = { dir: 'asc', sort: 'assignee', ...props.query }`?

**Review by eviljeff — APPROVED** [review]

File: pages/milestones/latest.js (hunk 1 above)
Comment (muffinresearch) [reply pages/milestones/latest.js:21]: Yep good catch, that's much more concise 👍
